### ISSUE TITLE
red5pro jar file

### ISSUE THREAD

**Issue by surabhi1694** [red5pro/streaming-android#67] opened 2017-02-21 17:51 UTC
hey i'm using your git codeto understand thestreaming but it gives me error that red5pro-1.2.0 jar is not available
i'm using android studio and noguat device please tell me if there is any comile lib to use red5pro or give me the solution.. please 
thank you

**Comment by HoldenMills** [comment] 2017-02-24 16:58
Did you clone the repository, or download the project onto your local system? 

Under build.gradle (Module: app), you will see the dependencies listed:
```dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'ch.qos.logback:logback-classic:1.1.2'
 compile 'ch.qos.logback:logback-core:1.1.2'
 compile 'org.apache.mina:mina-core:2.0.7'
 compile 'org.slf4j:slf4j-api:1.7.5'
 compile 'com.android.support:support-v4:23.1.1'
 compile files('libs/red5pro-1.0.2.jar')
}```
Please change the last line to ```( 'libs/red5pro-1.2.0.jar' )```

If that does not address your issue, please let me know.

**Comment by vaughnsoft** [comment] 2017-03-03 08:32
I've tried both ways, libs/red5pro-1.0.2.jar doesn't exist and it won't build without it.

**Comment by HoldenMills** [comment] 2017-03-03 18:33
I tested this myself and was able to install the application without any modifications.  What device are you using?  The latest SDK version is 2.1.0 so I'm not sure what is going on here.  What version of Android Studio are you using?

**Comment by vaughnsoft** [comment] 2017-03-03 22:29
Yes, latest SDK 2.1.0 and using a fresh install of Android Studio 2.3 with an Android Virtual Device.

**Comment by HoldenMills** [comment] 2017-03-06 19:15
Unfortunately, we do not support the use of virtual devices.  You will have to use a physical device to test.

**Comment by vaughnsoft** [comment] 2017-03-06 21:04
Okay. So I threw together a basic example using the link you gave, also
included the lib and libraries from the sdk zip. I'm able to get a camera
preview in the app, however I get an odd error when the app
reaches publish.publish(streamName, R5Stream.RecordType.Live);

E/AndroidRuntime: FATAL EXCEPTION: Thread-71872

 Process: vaughnsoft.marvin.deez4, PID: 26118

 java.lang.NoClassDefFoundError: Failed resolution of:
Lorg/apache/mina/core/buffer/IoBuffer;

 at com.red5pro.streaming.core.l.a(Unknown Source)

 at com.red5pro.streaming.R5Stream.write(Unknown Source)

 at com.red5pro.streaming.source.c.run(Unknown Source)

 at java.lang.Thread.run(Thread.java:818)

Caused by: java.lang.ClassNotFoundException: Didn't find class
"org.apache.mina.core.buffer.IoBuffer" on path: DexPathList[[zip file
"/data/app/vaughnsoft.marvin.deez4-2/base.apk", zip file
"/data/app/vaughnsoft.marvin.deez4-2/split_lib_dependencies_apk.apk", zip
file "/data/app/vaughnsoft.marvin.deez4-2/split_lib_slice_0_apk.apk", zip
file "/data/app/vaughnsoft.marvin.deez4-2/split_lib_slice_1_apk.apk", zip
file "/data/app/vaughnsoft.marvin.deez4-2/split_lib_slice_2_apk.apk", zip
file "/data/app/vaughnsoft.marvin.deez4-2/split_lib_slice_3_apk.apk", zip
file "/data/app/vaughnsoft.marvin.deez4-2/split_lib_slice_4_apk.apk", zip
file "/data/app/vaughnsoft.marvin.deez4-2/split_lib_slice_5_apk.apk", zip
file "/data/app/vaughnsoft.marvin.deez4-2/split_lib_slice_6_apk.apk", zip
file "/data/app/vaughnsoft.marvin.deez4-2/split_lib_slice_7_apk.apk", zip
file "/data/app/vaughnsoft.marvin.deez4-2/split_lib_slice_8_apk.apk", zip
file
"/data/app/vaughnsoft.marvin.deez4-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/vaughnsoft.marvin.deez4-2/lib/arm,
/data/app/vaughnsoft.marvin.deez4-2/base.apk!/lib/armeabi-v7a,
/data/app/vaughnsoft.marvin.deez4-2/split_lib_dependencies_apk.apk!/lib/armeabi-v7a,
/data/app/vaughnsoft.marvin.deez4-2/split_lib_slice_0_apk.apk!/lib/armeabi-v7a,
/data/app/vaughnsoft.marvin.deez4-2/split_lib_slice_1_apk.apk!/lib/armeabi-v7a,
/data/app/vaughnsoft.marvin.deez4-2/split_lib_slice_2_apk.apk!/lib/armeabi-v7a,
/data/app/vaughnsoft.marvin.deez4-2/split_lib_slice_3_apk.apk!/lib/armeabi-v7a,
/data/app/vaughnsoft.marvin.deez4-2/split_lib_slice_4_apk.apk!/lib/armeabi-v7a,
/data/app/vaughnsoft.marvin.deez4-2/split_lib_slice_5_apk.apk!/lib/armeabi-v7a,
/data/app/vaughnsoft.marvin.deez4-2/split_lib_slice_6_apk.apk!/lib/armeabi-v7a,
/data/app/vaughnsoft.marvin.deez4-2/split_lib_slice_7_apk.apk!/lib/armeabi-v7a,
/data/app/vaughnsoft.marvin.deez4-2/split_lib_slice_8_apk.apk!/lib/armeabi-v7a,
/data/app/vaughnsoft.marvin.deez4-2/split_lib_slice_9_apk.apk!/lib/armeabi-v7a,
/vendor/lib, /system/lib]]

 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)

 at java.lang.ClassLoader.loadClass(ClassLoader.java:511)

 at java.lang.ClassLoader.loadClass(ClassLoader.java:469)

 at com.red5pro.streaming.core.l.a(Unknown Source)

 at com.red5pro.streaming.R5Stream.write(Unknown Source)

 at com.red5pro.streaming.source.c.run(Unknown Source)

 at java.lang.Thread.run(Thread.java:818)

   Suppressed:
java.lang.ClassNotFoundException: org.apache.mina.core.buffer.IoBuffer

 at java.lang.Class.classForName(Native Method)

 at java.lang.BootClassLoader.findClass(ClassLoader.java:781)

 at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)

 at java.lang.ClassLoader.loadClass(ClassLoader.java:504)

  ... 5 more

Caused by: java.lang.NoClassDefFoundError: Class not found using the boot
class loader; no stack trace available


Here is the code I'm using:

package vaughnsoft.marvin.deez4;

import android.app.Activity;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.hardware.Camera;
import android.view.Surface;

import com.red5pro.streaming.R5Connection;
import com.red5pro.streaming.R5Stream;
import com.red5pro.streaming.R5StreamProtocol;
import com.red5pro.streaming.config.R5Configuration;
import com.red5pro.streaming.source.R5Camera;
import com.red5pro.streaming.source.R5Microphone;
import com.red5pro.streaming.view.R5VideoView;

public class MainActivity extends AppCompatActivity {

    protected R5VideoView preview;
    protected R5Stream publish;
    protected Camera cam;
    protected int camOrientation;

    private static String serverHost = "198.255.17.18";
    private static int serverPort = 8554;
    private static String serverApp = "live";
    private static Float serverBufferTime = 0.2f;

    private static int videoWidth = 360;
    private static int videoHeight = 640;
    private static int videoBitrate = 750;

    private static String streamName = "live_1234_zxcv";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        try {
            R5Configuration config = new
R5Configuration(R5StreamProtocol.RTSP, serverHost, serverPort, serverApp,
serverBufferTime);
            R5Connection connection = new R5Connection(config);
            //setup a new stream using the connection
            publish = new R5Stream(connection);
            R5Camera camera = null;
            //attach a camera video source
            cam = openFrontFacingCameraGingerbread();
            cam.setDisplayOrientation((camOrientation + 180) % 360);

            camera = new R5Camera(cam, videoWidth, videoHeight);
            camera.setBitrate(videoBitrate);
            camera.setOrientation(camOrientation);
            //attach a microphone
            R5Microphone mic = new R5Microphone();
            publish.attachMic(mic);

            preview = (R5VideoView) this.findViewById(R.id.videoPreview);

            preview.attachStream(publish);

            publish.attachCamera(camera);

            //preview.showDebugView(true);

            publish.publish(streamName, R5Stream.RecordType.Live);

            cam.startPreview();


        } catch (Exception e)
        {
            e.printStackTrace();
        }
    }
    protected Camera openFrontFacingCameraGingerbread() {
        int cameraCount = 0;
        Camera cam = null;
        Camera.CameraInfo cameraInfo = new Camera.CameraInfo();
        cameraCount = Camera.getNumberOfCameras();
        for (int camIdx = 0; camIdx < cameraCount; camIdx++) {
            Camera.getCameraInfo(camIdx, cameraInfo);
            if (cameraInfo.facing == Camera.CameraInfo.CAMERA_FACING_FRONT)
{
                try {
                    cam = Camera.open(camIdx);
                    camOrientation = cameraInfo.orientation;
                    //applyDeviceRotation();
                    break;
                } catch (RuntimeException e) {
                    e.printStackTrace();
                }
            }
        }

        return cam;
    }protected void applyDeviceRotation(){
        int rotation =
getActivity().getWindowManager().getDefaultDisplay().getRotation();
        int degrees = 0;
        switch (rotation) {
            case Surface.ROTATION_0: degrees = 0; break;
            case Surface.ROTATION_90: degrees = 90; break;
            case Surface.ROTATION_180: degrees = 180; break;
            case Surface.ROTATION_270: degrees = 270; break;
        }

        camOrientation += degrees;

        camOrientation = camOrientation%360;
    }

    public Activity getActivity() {
        return this;
    }
    @Override
    public void onStop() {

        if (publish != null){
            publish.stop();

            if(publish.getVideoSource() != null) {
                Camera c = ((R5Camera)
publish.getVideoSource()).getCamera();
                c.stopPreview();
                c.release();
            }
            publish = null;

        }

        super.onStop();
    }
}

**Comment by vaughnsoft** [comment] 2017-03-06 21:28
Nevermind, I'm an idiot. I left out the dependency in build.gradle


    compile 'org.apache.mina:mina-core:2.0.7'

**Comment by HoldenMills** [comment] 2017-03-07 20:21
Glad to hear you fixed it!  I will close this issue out then.  If you need anything else, please l[et me know](https://red5pro.zendesk.com/hc/en-us/requests/new)

**Closed by HoldenMills** 2017-03-07 20:21 UTC
